name: Waka Readme

on:
  schedule:
    # Runs at -
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Customize
          SHOW_LINES_OF_CODE : True
          SHOW_SHORT_INFO : False
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT : True
          SHOW_PROJECTS : False
          SHOW_EDITORS : True
          SYMBOL_VERSION : 2
          SHOW_LOC_CHART : False
          
